### ISSUE TITLE
error setting argument 0 when using CFRelease

### ISSUE THREAD

**Issue by owencm** [TooTallNate/NodObjC#62]
I've really enjoyed playing with NodObjC but am stumped by an issue I'm having. I'm creating objects with $.CGEventCreateMouseEvent and want to release them with $.CFRelease as follows:

    var $ = require('NodObjC');
    $.framework('Cocoa');

    var pool = $.NSAutoreleasePool('alloc')('init');

    var moveEvent = $.CGEventCreateMouseEvent(null, $.kCGEventMouseMoved, $.CGPointMake(100, 100), $.kCGMouseButtonLeft);
    $.CGEventPost($.kCGHIDEventTap, moveEvent);
    $.CFRelease('cf', moveEvent);

    pool('drain'); 

But I'm getting the following error:

    /Users/owencm/Desktop/node-macmouse/node_modules/ffi/lib/_foreign_function.js:54
          throw e
                ^
    TypeError: error setting argument 0 - writePointer: Buffer instance expected as third argument
        at TypeError (native)
        at Object.writePointer (/Users/owencm/Desktop/node-macmouse/node_modules/ffi/node_modules/ref/lib/ref.js:740:11)
        at Object.set (/Users/owencm/Desktop/node-macmouse/node_modules/ffi/node_modules/ref/lib/ref.js:482:13)
        at Object.alloc (/Users/owencm/Desktop/node-macmouse/node_modules/ffi/node_modules/ref/lib/ref.js:514:13)
        at ForeignFunction.proxy (/Users/owencm/Desktop/node-macmouse/node_modules/ffi/lib/_foreign_function.js:49:22)
        at Function.unwrapper (/Users/owencm/Desktop/node-macmouse/node_modules/NodObjC/lib/core.js:297:31)
        at Object.<anonymous> (/Users/owencm/Desktop/node-macmouse/test.js:8:7)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)

I've dug around a little in _foreign_function.js but can't seem to find the problem - is there something I'm doing wrong or is this an actual bug?

**Comment by TooTallNate** [comment]
[`CFRelease()`](https://developer.apple.com/library/ios/documentation/CoreFoundation/Reference/CFTypeRef/#//apple_ref/c/func/CFRelease) only appears to take a single argument, a CFTypeRef. So I'm not sure why you're passing in the `'cf'` string, you probably only need to pass the `moveEvent` in as the first argument.
