### ISSUE TITLE
Can't read property of object

### ISSUE THREAD

**Issue by hinzundcode** [TooTallNate/NodObjC#66]
``` js
var $ = require("nodobjc");

$.framework("Foundation");
$.framework("AppKit");

var app = $.NSWorkspace("sharedWorkspace")("activeApplication");
console.log(app.ivar("NSApplicationName"));
```

```
node_modules/nodobjc/lib/core.js:181
    var basetype = type.type ? type.type : type;
                       ^
TypeError: Cannot read property 'type' of null
    at Object.wrapValue (/Users/chris/test4/node_modules/nodobjc/lib/core.js:181:24)
    at ID.module.exports.ID.ivar (/Users/chris/test4/node_modules/nodobjc/lib/id.js:74:19)
    at Object.<anonymous> (/Users/chris/test4/test.js:7:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by SidneyS** [comment]
I have the same problem. Accessing the "layer" property of any object is does never work.

avPlayerLayer = ObjC.AVPlayerLayer('playerLayerWithPlayer', avPlayerPlayer);

avPlayerLayer.layer is undefined  - always..

**Comment by agentcooper** [comment]
@hinzundcode I had success with the following code

```js
const $ = require('nodobjc');

$.framework('Foundation');
$.framework('AppKit');

const app =
  $.NSWorkspace
    ('sharedWorkspace')
    ('runningApplications')
    (
      'filteredArrayUsingPredicate',
      $.NSPredicate('predicateWithFormat', $('active == YES'))
    )
    ('objectAtIndex', 0)
    ('localizedName');

console.log(app);
```
